[build]
  command = "npm ci --prefer-offline && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_CACHE = "/opt/buildhome/.npm"
  NPM_CONFIG_PREFER_OFFLINE = "true"

# Build Cache
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Build Cache
[[plugins]]
  package = "@netlify/plugin-cache"
  [plugins.inputs]
    paths = ["node_modules/.cache", ".vite"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific routes for better handling
[[redirects]]
  from = "/malls/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/search"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
